p:
  family: 'CG'             
  degree: 1

u:
  family: 'CG'             
  degree: 4

sigma: 
  family: 'RT'             
  degree: 4

w:
  family: 'CG'             
  degree: 4

q:
  family: 'CG'             
  degree: 4
